[versions]
androidxannotations = "1.7.1"
androidxactivity = "1.8.2"
androidxnavigation = "2.7.6"
androidxpreference = "1.2.1"

compose = "2023.10.01"
composeMaterial3 = "1.0.1"
compose-compiler = "1.5.6"

gradleNexusStagingPlugin = "0.30.0"
publishPlugin = "1.3.0"

agp = "8.2.0"
compose-plugin = "1.5.11"
kotlin = "1.9.21"

android-minSdk = "24"
android-compileSdk = "34"
android-targetSdk = "34"

multiplatformSettings = "1.1.1"

namespace = "com.alorma.compose.settings"

[libraries]
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "androidxannotations"}
androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "androidxactivity" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "androidxnavigation" }
androidx-preference-preference = { module = "androidx.preference:preference", version.ref = "androidxpreference" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "androidxpreference" }

plugin-gradle-nexus-staging = { module = "io.codearte.gradle.nexus:gradle-nexus-staging-plugin", version.ref = "gradleNexusStagingPlugin" }
plugin-gradle-publish = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "publishPlugin" }

multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatform-settings-noArg = { module = "com.russhwolf:multiplatform-settings-no-arg", version.ref = "multiplatformSettings" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }

jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }